# -*- coding: utf-8 -*-
"""Driver Drowziness Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7fwL8B-SffWZ44CQmBZZx5tVo66T_8I
"""

import os
import shutil
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import (confusion_matrix,
                             classification_report,
                             accuracy_score,
                             precision_score,
                             recall_score,
                             f1_score)
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (Conv2D,
                                     MaxPooling2D,
                                     Dense,
                                     Flatten,
                                     Dropout,
                                     BatchNormalization,
                                     GlobalAveragePooling2D)
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import (EarlyStopping,
                                        ModelCheckpoint,
                                        ReduceLROnPlateau)
from tensorflow.keras.utils import plot_model
from google.colab import drive
import gdown
import zipfile

from google.colab import drive
drive.mount('/content/drive')

file_id = "1Rj0EYgDy0sy7jc7-KXvQiHwpqA0Dzj__"
url = f"https://drive.google.com/uc?id={file_id}"
gdown.download(url, "dataset.zip", quiet=False)

import zipfile
with zipfile.ZipFile("dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/dataset")

source = "dataset/train"
classes = ["Open", "Closed", "yawn", "no_yawn"]

for cls in classes:
    images = os.listdir(os.path.join(source, cls))
    train, test = train_test_split(images, test_size=0.2, random_state=42)

    for split, files in [("train", train), ("test", test)]:
        os.makedirs(f"dataset_split/{split}/{cls}", exist_ok=True)
        for f in files:
            shutil.copy(f"{source}/{cls}/{f}", f"dataset_split/{split}/{cls}/{f}")

    print(f"{cls}: {len(train)} train, {len(test)} test")

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.2,
    brightness_range=[0.8, 1.2],
    horizontal_flip=True,
    validation_split=0.2
)


test_datagen = ImageDataGenerator(rescale=1./255)


train_data = train_datagen.flow_from_directory(
    "dataset_split/train",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training",
    seed=42
)

val_data = train_datagen.flow_from_directory(
    "dataset_split/train",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation",
    seed=42
)

test_data = test_datagen.flow_from_directory(
    "dataset_split/test",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)


print("Class indices:", train_data.class_indices)
print("Train batches:", len(train_data))
print("Val   batches:", len(val_data))
print("Test  batches:", len(test_data))

def build_custom_cnn():
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=(224, 224, 3)),
        BatchNormalization(),
        MaxPooling2D(2,2),

        Conv2D(64, (3,3), activation='relu'),
        BatchNormalization(),
        MaxPooling2D(2,2),

        Conv2D(128, (3,3), activation='relu'),
        BatchNormalization(),
        MaxPooling2D(2,2),

        Flatten(),
        Dense(256, activation='relu'),
        Dropout(0.5),
        Dense(4, activation='softmax')
    ])
    return model

cnn_model = build_custom_cnn()
cnn_model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
cnn_model.summary()

def build_mobilenet_model():
    base_model = MobileNetV2(input_shape=(224, 224, 3),
                              include_top=False,
                              weights='imagenet')
    base_model.trainable = False

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.4)(x)
    output = Dense(4, activation='softmax')(x)

    model = Model(inputs=base_model.input, outputs=output)
    return model

mobilenet_model = build_mobilenet_model()
mobilenet_model.compile(optimizer=Adam(learning_rate=0.001),
                        loss='categorical_crossentropy',
                        metrics=['accuracy'])
mobilenet_model.summary()

cnn_model = build_custom_cnn()
cnn_model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

mobilenet_model = build_mobilenet_model()
mobilenet_model.compile(optimizer=Adam(learning_rate=0.001),
                        loss='categorical_crossentropy',
                        metrics=['accuracy'])

callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True, monitor='val_loss'),
    ModelCheckpoint("best_cnn.h5",       save_best_only=True, monitor='val_accuracy'),
]

cnn_hyistor = cnn_model.fit(
    train_data,
    validation_data=val_data,
    epochs=20,
    callbacks=callbacks
)

callbacks_mn = [
    EarlyStopping(patience=5, restore_best_weights=True, monitor='val_loss'),
    ModelCheckpoint("best_mobilenet.h5", save_best_only=True, monitor='val_accuracy'),
]

mobilenet_history = mobilenet_model.fit(
    train_data,
    validation_data=val_data,
    epochs=20,
    callbacks=callbacks_mn
)

cnn_loss, cnn_acc             = cnn_model.evaluate(test_data)
mobilenet_loss, mobilenet_acc = mobilenet_model.evaluate(test_data)

print(f"Custom CNN     — Test Accuracy: {cnn_acc:.4f}")
print(f"MobileNetV2    — Test Accuracy: {mobilenet_acc:.4f}")

test_data.reset()
y_pred        = mobilenet_model.predict(test_data)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true        = test_data.classes

label_names = list(test_data.class_indices.keys())

cm = confusion_matrix(y_true, y_pred_classes)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=label_names,
            yticklabels=label_names,
            cmap='Blues')
plt.title("Confusion Matrix — MobileNetV2")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print(classification_report(y_true, y_pred_classes, target_names=label_names))

class_indices = train_data.class_indices
inv_map = {v: k for k, v in class_indices.items()}
print("Class mapping:", inv_map)  # e.g. {0: 'Closed', 1: 'Open', 2: 'no_yawn', 3: 'yawn'}

def classify_fatigue(pred_index):
    label = inv_map[pred_index]
    if label in ["Open", "no_yawn"]:
        return 0, "Alert"
    elif label == "yawn":
        return 1, "Mild Fatigue"
    elif label == "Closed":
        return 2, "Severe Fatigue"

fatigue_results = [classify_fatigue(p) for p in y_pred_classes]

for pred, (stage, label) in zip(y_pred_classes[:10], fatigue_results[:10]):
    print(f"Predicted class: {inv_map[pred]:<10} → Fatigue Stage: {label}")

fatigue_stages = [stage for stage, label in fatigue_results]

interval = 10
time_points = []
avg_fatigue = []

for i in range(0, len(fatigue_stages), interval):
    chunk = fatigue_stages[i:i+interval]
    avg_fatigue.append(np.mean(chunk))
    time_points.append(i // interval)

plt.figure(figsize=(12, 5))
plt.plot(time_points, avg_fatigue, marker='o', color='crimson', linewidth=2)
plt.axhline(y=0.5, color='orange', linestyle='--', label='Alert → Mild threshold')
plt.axhline(y=1.5, color='red',    linestyle='--', label='Mild → Severe threshold')
plt.yticks([0, 1, 2], ["Alert", "Mild Fatigue", "Severe Fatigue"])
plt.xlabel("Time Interval")
plt.ylabel("Fatigue Level")
plt.title("Driver Fatigue Progression Curve")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()